"""*initial*

Revision ID: 46824a5118d9
Revises:
Create Date: 2025-09-03 12:21:09.444100

"""



# revision identifiers, used by Alembic.
revision = "46824a5118d9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
