"""add files and metadata

Revision ID: 9b1dfae114de
Revises: 9bca1fa8d0cc
Create Date: 2025-09-05 19:30:50.216934

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9b1dfae114de"
down_revision = "9bca1fa8d0cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column(
            "file_type", sa.Enum("PDF", "DOC", "DOCX", name="filetype"), nullable=False
        ),
        sa.Column(
            "visibility",
            sa.Enum("PRIVATE", "DEPARTMENT", "PUBLIC", name="visibility"),
            nullable=False,
        ),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("s3_key", sa.String(length=255), nullable=False),
        sa.Column("download_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], name=op.f("files_department_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("files_owner_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("files_pkey")),
        sa.UniqueConstraint("id", name=op.f("files_id_key")),
        sa.UniqueConstraint("s3_key", name=op.f("files_s3_key_key")),
    )
    op.create_table(
        "file_metadata",
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("paragraph_count", sa.Integer(), nullable=True),
        sa.Column("table_count", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("creation_date", sa.String(length=50), nullable=True),
        sa.Column("creator", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("file_metadata_file_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("file_metadata_pkey")),
        sa.UniqueConstraint("file_id", name=op.f("file_metadata_file_id_key")),
        sa.UniqueConstraint("id", name=op.f("file_metadata_id_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_metadata")
    op.drop_table("files")
    # ### end Alembic commands ###
