"""init_models

Revision ID: 6e4296d47211
Revises: 46824a5118d9
Create Date: 2025-09-04 18:00:10.711758

"""



# revision identifiers, used by Alembic.
revision = "6e4296d47211"
down_revision = "46824a5118d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
